- name: Stop slapd
  service: name=slapd state=stopped enabled=false
  ignore_errors: yes
  
- name: Uninstall slapd
  apt: name=slapd state=absent purge=yes

- name: Remove /var/lib/ldap
  file: path=/var/lib/ldap state=absent

- name: Remove certs
  file: path="{{ cert_path }}/slapd*" state=absent

# stop playbook execution
# - name: Uninstalled
  # meta: end_play
