# ansible-playbook playbook.yml -i hosts -v
# or if you want to run specifieds roles:
# ansible-playbook playbook.yml -i hosts -v --tag common

---
- name: OpenLDAP with EduPerson schema 2016 memberOf
  hosts: all
  become: yes
  vars:
    org: unical
    hostname:   testunical
    domain1: it
    domain: "{{ hostname }}.{{ domain1 }}"
    
    fqdn: "ldap.{{ domain }}"
    
    cert_path: "/etc/ssl/certs/{{ domain }}"
    ldap_ca_cert: slapd-cacert.pem
    ldap_server_cert: slapd-cert.pem
    ldap_server_key: slapd-key.pem
    
    ldap_backend: "mdb"
    ldap_basedc: "dc={{ hostname }},dc={{ domain1 }}"
    ldap_basedn: "ou=people,dc={{ hostname }},dc={{ domain1 }}"
    ldap_pw: slapdsecret
    ldap_monitor_pw: monitorsecret

    debug_level: 0
    
    # dir where template will be rendered (also for debug purpose)
    tmp_dir: /tmp/ansible-slapd-tmp

    # import fake users declared in roles/slapd/templates/entries/entries-people.ldif
    # you can even import them using csv file and csv2ldif.py script (modify attributes mapping if needed)
    import_example_users: true

    backup_folder: "backups/{{ lookup('pipe', 'date +%Y-%m-%d_%H%M') }}"
    restore_ldif_path: "backups/example"

  roles:
    - { role: slapd_backup, tags: ["slapd_backup"] }
    - { role: slapd_uninstall, tags: ["slapd_uninstall"] }
    - { role: slapd_install, tags: ["slapd_install"] }
    - { role: slapd_configure, tags: ["slapd_configure"] }
    # use backup/example structure to restore a complete slapd configuration with entries
    # - { role: slapd_restore_backup, tags: ["slapd_restore_backup"] }
    - { role: slapd_test, tags: ["slapd_test"] }  
