# ansible-playbook playbook.yml -i hosts -v
# or if you want to run specifieds roles:
# ansible-playbook playbook.yml -i hosts -v --tag common

---
- name: OpenLDAP with EduPerson schema 2016 memberOf
  hosts: all
  become: yes
  vars:
    org: unical
    hostname:   testunical
    domain1: it
    domain: "{{ hostname }}.{{ domain1 }}"
    
    fqdn: "ldap.{{ domain }}"
    
    cert_path: "/etc/ssl/certs/{{ domain }}"
    ldap_ca_cert: slapd-cacert.pem
    ldap_server_cert: slapd-cert.pem
    ldap_server_key: slapd-key.pem
    
    ldap_backend: "mdb"
    ldap_basedc: "dc={{ hostname }},dc={{ domain1 }}"
    ldap_basedn: "ou=people,dc={{ hostname }},dc={{ domain1 }}"
    # ldap_binddn: "cn=search,ou=system,dc={{ hostname }},dc={{ domain1 }}"
    ldap_pw: slapdsecret
    
  roles:
    - { role: slapd, tags: ["slapd"] }    
