# CLEANUPS
- name: "Purge openLDAP"
  import_tasks: cleanup.yml
# END CLEANUPS

# Dependencies
- name: "Install and Configure openLDAP"
  import_tasks: install.yml

- name: Render template directory-config_nocert.ldif
  template: 
    src: roles/slapd/templates/directory-config_nocert.ldif
    dest: /tmp/directory-config_nocert.ldif

- name: Apply Directory config ldif
  command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/directory-config_nocert.ldif"

# Schemas
- name: "Import Schemas"
  import_tasks: schemas.yml
# End Schemas

- name: Render template organizational-units.ldif
  template: 
    src: roles/slapd/templates/organizational-units.ldif
    dest: /tmp/organizational-units.ldif

- name: Add Directory content ldif
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/organizational-units.ldif"

- name: Render template organizational-units.ldif
  template: 
    src: roles/slapd/templates/entries/{{ item }}
    dest: /tmp/{{ item }}
  with_items:
    - "entries-system.ldif"
    - "entries-people.ldif"
    - "entries-groups.ldif"

# - name: Add OU system entries
  # command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/{{ item }}"
  # with_items:
    # - "entries-system.ldif"

- name: Add OU entries (groups)
  command: "ldapadd -x -D 'cn=admin,{{ ldap_basedc }}' -w {{ ldap_pw }}  -H ldapi:/// -f /tmp/{{ item }}"
  with_items:
    - "entries-groups.ldif"

- name: Add OU entries (peoples)
  command: "ldapadd -x -D 'cn=admin,{{ ldap_basedc }}' -w {{ ldap_pw }}  -H ldapi:/// -f /tmp/{{ item }}"
  with_items:
    - "entries-people.ldif"
  when: import_example_users == True
  
# overlays
- name: "Import Overlays"
  import_tasks: overlays.yml
# end overlays

# ldaps
- name: "Enable ldaps"
  import_tasks: ldaps.yml
# end ldaps

- name: Clean temporary config ldif
  file:
    state: absent
    path: "tmp/*.ldif"
